# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    
    - name: Test api
      run: cd server&&go test -v ./api

    - name: Test sqlite
      run: cd server&&go test -v ./db

    - name: Test graphql
      run: cd server&&go test -v ./db/wp

    - name: Test download
      run: cd server&&go test -v ./download

    - name: Build linux-amd64
      run: cd server&&env GOOS=linux GOARCH=amd64 go build -v .

    - name: Upload linux-amd64 artifact
      uses: actions/upload-artifact@v3
      with: 
        name: linux
        path: ./server/go-svelte

    - name: Build Windows-amd64
      run: cd server&&env GOOS=windows GOARCH=amd64 go build -v .
      
    - name: Upload Windows-amd64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows-amd64
        path: ./server/go-svelte.exe
